### ISSUE TITLE
Broken links

### ISSUE THREAD

**Issue by ndsvw** [kdeldycke/awesome-billing#75]
Hi, I found some broken links:

- [x] https://developers.google.com/ad-manager/api/reference/v201911/CompanyService.BillingCap (file: README.md, status code: 404)
- [x] https://agoric.com/assets/pdf/papers/incentive-engineering-for-computational-resource-management.pdf (file: README.md, status code: 404)
- [x] https://vita.mcafee.cc/PDF/EconPublicCloud.pdf (file: README.md, status code: 526)
- [x] http://www.dwmbeancounter.com/tutorial/Tutorial.html (file: README.md, status code: 404)
- [x] https://amzn.com/0273744704/?tag=kevideld-20 (file: README.md, status code: 404)
- [x] https://amzn.com/1422119157/?tag=kevideld-20 (file: README.md, error: ECONNRESET)
- [x] https://amzn.com/9814287113/?tag=kevideld-20 (file: README.md, status code: 404)
- [x] https://ec.europa.eu/growth/smes/support/late-payment_en (file: README.md, status code: 404)
- [x] https://github.com/trustly/pci-blackbox (file: README.md, status code: 404)
- [x] https://developer.apple.com/design/human-interface-guidelines/subscriptions/overview/ (file: README.md, status code: 404)
- [x] https://baremetrics.com/blog/saas-financial-model (file: README.md, error: ECONNREFUSED)
- [x] http://www.eusprig.org/horror-stories.htm (file: README.md, status code: 404)
- [x] https://www.prosperops.com/wp-content/uploads/ris_and_savings_plans.png (file: README.md, status code: 404)
- [x] https://www.orbitera.com (file: README.md, error: ENOTFOUND)

**Comment by kdeldycke** [comment]
Thanks @ndsvw for the detailed list! Just fixed all of them upstream!
