### ISSUE TITLE
Volcano has been archived 

### ISSUE THREAD

**Issue by pydubreucq** [kdeldycke/awesome-billing#97]
Hi Kévin,
Volcano hasard been archived 
https://github.com/volcano/volcano
Bye

**Comment by kdeldycke** [comment]
Oh good point @pydubreucq. I couldn't find any trace or evidence that the project has beed forked or rebooted in any way.

So I removed the entry from the list in 71e3afc35f9d4e55cf491639510d0b8bc64a2f85. We'll add back any derivates of this project if someone detects signs of life.
